### ISSUE TITLE
Type ... is not assignable to type 'never'.ts(2322)

### ISSUE THREAD

**Issue by guyellis** [TCMiranda/joi-extract-type#20]
I'm getting the error described in the comments at the bottom of the example below which is also available [in a repo here](https://github.com/guyellis/joi-extract-type-example).

Am I just approaching this incorrectly or is this something that can be fixed in this repo?

```javascript
import joi from '@hapi/joi';
import 'joi-extract-type';

const testSchema = joi
  .object({
  tractor: joi
    .array()
    .has(
      joi.object({
        myId: joi
        .string()
        .optional(),
      })
    )
    .required()
    .min(1),
  })
  .required();

type TestType = joi.extractType<typeof testSchema>;

const tf = (): TestType => {
  return {
    tractor: [{ myId: '1' }]
  };
  // On myId above I'm getting this TypeScript error:
  // (property) myId: string
  // Type 'string' is not assignable to type 'never'.ts(2322)
}
```

**Comment by TCMiranda** [comment]
Hey @guyellis I think `.has` is not implemented.
Any reason to use .has instead of .items?

Actually I haven't used `.has` myself, and I am not sure how it would map to a type since the implementation says that it is valid if at least one of array items match the schema.

https://hapi.dev/family/joi/?v=16.1.2#arrayhasschema

**Comment by guyellis** [comment]
@TCMiranda - no reason not to use items - that works - thanks!
